/* GENERATED by tools/gen_weather_icons.py -- do not edit by hand.
 *
 * Glyphs from Erik Flowers' Weather Icons (SIL OFL 1.1), subset to the
 * codepoints listed in tools/weather_icons.txt. Regenerate with:
 *   ./tools/gen_weather_icons.py
 */
#pragma once

#include "lvgl.h"

LV_FONT_DECLARE(weather_font_56);
LV_FONT_DECLARE(weather_font_32);

#define WI_DAY_SUNNY         "\xEF\x80\x8D"   /* U+F00D wi-day-sunny */
#define WI_DAY_CLOUDY        "\xEF\x80\x82"   /* U+F002 wi-day-cloudy */
#define WI_CLOUDY            "\xEF\x80\x93"   /* U+F013 wi-cloudy */
#define WI_FOG               "\xEF\x80\x94"   /* U+F014 wi-fog */
#define WI_SPRINKLE          "\xEF\x80\x9C"   /* U+F01C wi-sprinkle */
#define WI_RAIN              "\xEF\x80\x99"   /* U+F019 wi-rain */
#define WI_SNOW              "\xEF\x80\x9B"   /* U+F01B wi-snow */
#define WI_SHOWERS           "\xEF\x80\x9A"   /* U+F01A wi-showers */
#define WI_THUNDERSTORM      "\xEF\x80\x9E"   /* U+F01E wi-thunderstorm */
#define WI_NIGHT_CLEAR       "\xEF\x80\xAE"   /* U+F02E wi-night-clear */
#define WI_NIGHT_ALT_CLOUDY  "\xEF\x82\x86"   /* U+F086 wi-night-alt-cloudy */
#define WI_NIGHT_ALT_RAIN    "\xEF\x80\xA8"   /* U+F028 wi-night-alt-rain */
#define WI_HUMIDITY          "\xEF\x81\xBA"   /* U+F07A wi-humidity */
#define WI_STRONG_WIND       "\xEF\x81\x90"   /* U+F050 wi-strong-wind */
#define WI_THERMOMETER       "\xEF\x81\x95"   /* U+F055 wi-thermometer */
#define WI_RAINDROP          "\xEF\x81\xB8"   /* U+F078 wi-raindrop */
