#!/usr/bin/env python3
"""Generate LVGL fonts from Erik Flowers' Weather Icons.

Reads the icon names you want from a list file, looks their codepoints up in
the upstream CSS, subsets the TTF with lv_font_conv, and writes both the font
C files and a header of UTF-8 defines. Adding an icon is then one line in the
list file plus a re-run -- no hand-copied codepoints.

    ./tools/gen_weather_icons.py                 # generate from the list file
    ./tools/gen_weather_icons.py --list          # show every available icon
    ./tools/gen_weather_icons.py --list rain     # ...filtered

Weather Icons is SIL OFL 1.1. Requires node/npx for lv_font_conv.
"""

import argparse
import os
import re
import subprocess
import sys
import urllib.request

REPO = "https://raw.githubusercontent.com/erikflowers/weather-icons/master"
FONT_URL = f"{REPO}/font/weathericons-regular-webfont.ttf"
CSS_URL = f"{REPO}/css/weather-icons.css"

HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT = os.path.dirname(HERE)
CACHE = os.path.join(HERE, ".cache")
DEFAULT_LIST = os.path.join(HERE, "weather_icons.txt")
DEFAULT_OUT = os.path.join(PROJECT, "main", "icons")

# `.wi-day-sunny:before {` ... `content: "\f00d";`
RULE_RE = re.compile(r"^\.(wi-[a-z0-9-]+):before\s*\{")
CONTENT_RE = re.compile(r'content:\s*"\\([0-9a-fA-F]{4})"')


def fetch(url, path):
    """Download once and cache; the upstream files never change per release."""
    if os.path.exists(path):
        return path
    os.makedirs(os.path.dirname(path), exist_ok=True)
    print(f"  fetching {os.path.basename(path)}")
    with urllib.request.urlopen(url) as response, open(path, "wb") as out:
        out.write(response.read())
    return path


def parse_css(path):
    """name -> codepoint int. Later duplicates win, matching CSS cascade."""
    icons = {}
    pending = None
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            match = RULE_RE.match(line.strip())
            if match:
                pending = match.group(1)
                continue
            if pending:
                content = CONTENT_RE.search(line)
                if content:
                    icons[pending] = int(content.group(1), 16)
                    pending = None
                elif "}" in line:
                    pending = None
    return icons


def read_list(path):
    names = []
    with open(path, encoding="utf-8") as handle:
        for line in handle:
            line = line.split("#", 1)[0].strip()
            if line:
                names.append(line)
    return names


def c_identifier(name):
    """wi-day-sunny -> WI_DAY_SUNNY"""
    return name.replace("-", "_").upper()


def utf8_escape(codepoint):
    """Codepoint -> a C string literal of \\xNN bytes."""
    return "".join(f"\\x{byte:02X}" for byte in chr(codepoint).encode("utf-8"))


def generate_font(font, size, bpp, codepoints, out_dir):
    name = f"weather_font_{size}"
    target = os.path.join(out_dir, f"{name}.c")
    ranges = ",".join(f"0x{cp:04X}" for cp in codepoints)
    command = [
        "npx", "--yes", "lv_font_conv@latest",
        "--font", font,
        "--size", str(size),
        "--bpp", str(bpp),
        "--format", "lvgl",
        "--lv-include", "lvgl.h",
        "--no-compress",
        "--symbols", "",
        "--range", ranges,
        "-o", target,
    ]
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        sys.exit(f"lv_font_conv failed for size {size}:\n{result.stderr}")
    return name, target


def write_header(path, names, icons, sizes):
    lines = [
        "/* GENERATED by tools/gen_weather_icons.py -- do not edit by hand.",
        " *",
        " * Glyphs from Erik Flowers' Weather Icons (SIL OFL 1.1), subset to the",
        " * codepoints listed in tools/weather_icons.txt. Regenerate with:",
        " *   ./tools/gen_weather_icons.py",
        " */",
        "#pragma once",
        "",
        '#include "lvgl.h"',
        "",
    ]
    for size in sizes:
        lines.append(f"LV_FONT_DECLARE(weather_font_{size});")
    lines.append("")
    width = max(len(c_identifier(n)) for n in names) + 1
    for name in names:
        codepoint = icons[name]
        ident = c_identifier(name).ljust(width)
        lines.append(f'#define {ident} "{utf8_escape(codepoint)}"'
                     f"   /* U+{codepoint:04X} {name} */")
    lines.append("")
    with open(path, "w", encoding="utf-8") as handle:
        handle.write("\n".join(lines))


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--list", nargs="?", const="", metavar="FILTER",
                        help="list available icons (optionally filtered) and exit")
    parser.add_argument("--icons", default=DEFAULT_LIST, help="icon name list file")
    parser.add_argument("--sizes", nargs="+", type=int, default=[56, 32])
    parser.add_argument("--bpp", type=int, default=4, choices=[1, 2, 4, 8])
    parser.add_argument("--font", help="local TTF instead of downloading")
    parser.add_argument("--out", default=DEFAULT_OUT, help="output directory")
    args = parser.parse_args()

    css = fetch(CSS_URL, os.path.join(CACHE, "weather-icons.css"))
    icons = parse_css(css)

    if args.list is not None:
        matches = {n: c for n, c in icons.items() if args.list in n}
        for name in sorted(matches):
            print(f"  {name:<34} U+{matches[name]:04X}")
        print(f"\n{len(matches)} of {len(icons)} icons")
        return

    font = args.font or fetch(FONT_URL, os.path.join(CACHE, "weathericons.ttf"))
    names = read_list(args.icons)

    unknown = [n for n in names if n not in icons]
    if unknown:
        sys.exit("Unknown icon name(s): " + ", ".join(unknown) +
                 "\nRun with --list to see what is available.")

    # Duplicate codepoints are fine for lv_font_conv but waste a define.
    codepoints = sorted({icons[n] for n in names})
    os.makedirs(args.out, exist_ok=True)

    print(f"Generating {len(codepoints)} glyphs at {args.bpp}bpp")
    total = 0
    for size in args.sizes:
        name, target = generate_font(font, size, args.bpp, codepoints, args.out)
        size_kb = os.path.getsize(target) / 1024
        total += size_kb
        print(f"  {name:<20} {size_kb:7.1f} KB")

    header = os.path.join(args.out, "wi_glyphs.h")
    write_header(header, names, icons, args.sizes)
    print(f"  {'wi_glyphs.h':<20} {len(names)} defines")
    print(f"\nTotal {total:.1f} KB. Map codepoints to WMO codes in icons.c.")


if __name__ == "__main__":
    main()
